pool:
  vmImage: 'windows-latest'

steps:
- task: UseNode@1
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    choco install yarn -y
  displayName: 'install yarn'

- script: |
    yarn install
  displayName: 'yarn install'

- script: |
    yarn ci:test
  displayName: 'yarn ci:test'
  
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build/'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
